In [26]:
import numpy as np
import scipy
from sklearn.preprocessing import normalize

import sys
sys.path.append('./src')
import algorithms_approx3 as LcGD

In [37]:

n = 3
def generate_adj(n):
    A = np.random.choice(3, size=(n, n))
    np.fill_diagonal(A, 0.)
    A = normalize(A, axis=1, norm='l1')
    return A
A = generate_adj(n)

I = np.identity(n)
z_eq = np.random.uniform(size=(n, 1))
s = (I + I-A) @ z_eq
assert np.all((z_eq - np.linalg.inv(I + np.diag(A.sum(axis=1)) - A) @ s) < 1e-9)

In [92]:
ε = 1e-6
λ = .5
#A1 = generate_adj(n)
#A2 = generate_adj(n)
#A3 = λ*A1+(1-λ)*A2
s=np.array([[1], [0], [-1]])
z_eq1, _ = scipy.sparse.linalg.bicg(2*I - A1, s, tol=ε)
z_eq1 = z_eq1.reshape((len(s), 1))
z_eq2, _ = scipy.sparse.linalg.bicg(2*I - A2, s, tol=ε)
z_eq2 = z_eq2.reshape((len(s), 1))
z_eq3, _ = scipy.sparse.linalg.bicg(2*I - A3, s, tol=ε)
z_eq3 = z_eq3.reshape((len(s), 1))

print(LcGD.objective_f(z_eq3, A3) < λ*LcGD.objective_f(z_eq1, A1) + (1-λ)*LcGD.objective_f(z_eq2, A2))
LcGD.objective_f(z_eq3, A3), λ*LcGD.objective_f(z_eq1, A1) + (1-λ)*LcGD.objective_f(z_eq2, A2)

False


(0.8748480741922038, 0.8419321329639888)

In [76]:
print(A1, "\n\n", A2)

[[0.         1.         0.        ]
 [0.66666667 0.         0.33333333]
 [1.         0.         0.        ]] 

 [[0.         1.         0.        ]
 [0.33333333 0.         0.66666667]
 [0.         1.         0.        ]]


In [83]:
dis = 0
for i in range(n):
    for j in range(n):
        dis += A[i, j] * (s[i] - s[j])**2

In [84]:
dis

array([6.5])

In [91]:

s.T @ (I+np.diag(A.sum(axis=0)) -2*A)@ s

array([[6.5]])

---

# Contro esempio

In [33]:
A3

array([[0.        , 0.45      , 0.05      , 0.5       ],
       [0.        , 0.        , 0.03333333, 0.96666667],
       [0.63333333, 0.33333333, 0.        , 0.03333333],
       [0.42666667, 0.21333333, 0.36      , 0.        ]])

In [34]:
A1

array([[0.        , 0.5       , 0.        , 0.5       ],
       [0.        , 0.        , 0.        , 1.        ],
       [0.66666667, 0.33333333, 0.        , 0.        ],
       [0.4       , 0.2       , 0.4       , 0.        ]])

In [35]:
A2

array([[0.        , 0.        , 0.5       , 0.5       ],
       [0.        , 0.        , 0.33333333, 0.66666667],
       [0.33333333, 0.33333333, 0.        , 0.33333333],
       [0.66666667, 0.33333333, 0.        , 0.        ]])

1.219668770129891