In [8]:
import numpy as np
import scipy
from sklearn.preprocessing import normalize

In [14]:
n = 10
A = np.random.uniform(0, 7, (n, n)) * np.random.randint(0, 2, (n, n))
A = normalize(A, axis=1, norm="l1")
A = scipy.sparse.csr_matrix(A)
s = np.random.uniform(0, 1, (n, 1))

In [24]:
def neutral_view_heuristic_dir(A, s: np.matrix, verbosity: int = 0):
    Is, Js = np.nonzero(A)
    A_neutral_heur = A.copy()
    A_neutral_heur.data = np.array(1/np.absolute(s[Js])).flatten()**2
   
    # make row-stochastic
    A_neutral_heur = normalize(A_neutral_heur, axis=1, norm='l1')
    
    return A_neutral_heur, [], None

In [25]:
neutral_view_heuristic_dir(A, s)

(<10x10 sparse matrix of type '<class 'numpy.float64'>'
 	with 45 stored elements in Compressed Sparse Row format>,
 [],
 None)

In [22]:
# CHECK MEMORY USAGE
import subprocess
import re
import pandas as pd

def mem():

    cmd = subprocess.check_output("""top -bn 1 -o RES | grep -E "^( |[0-9])" | awk '{ printf("%-8s  %-8s  %-8s\\n", $2, $9, $10); }'""",
                              shell=True, universal_newlines=True)
    cmd = cmd.split('\n')

    data = []
    for line in cmd[1:]:
        if line == '':
            continue
        user, pcpu, pmem = re.split(r'\s+', line.strip())
        pmem = pmem.split(',')[0] #+'.'+ pmem.split(',')[1] 
        data.append([user, pcpu, float(pmem)])

    columns = re.split(r'\s+', cmd[0].strip())
    df = pd.DataFrame(data, columns=columns).groupby('USER').sum().sort_values('%MEM', ascending=False)
    df = df[(df.index != 'root') & (df['%MEM'] >= 0.5)]

    msg =  "*Top users by memory usage:*\n```" + df.to_string() + '```'
    return msg

print(mem())

*Top users by memory usage:*
```          %MEM
USER          
apotra    29.8
guidoba+  16.5
fcinus     3.0
corrado    2.5
jacopo.+   2.2
andreac+   2.2
spoetto    1.8
yanxia     1.2```


/tmp/ipykernel_735510/1811591593.py:21: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df = pd.DataFrame(data, columns=columns).groupby('USER').sum().sort_values('%MEM', ascending=False)


In [23]:
import numpy as np

In [26]:
s = np.matrix([1,2,3]).reshape(3, 1)

In [32]:
np.ones((3,1))@np.multiply(s, s).T

matrix([[1., 4., 9.],
        [1., 4., 9.],
        [1., 4., 9.]])

In [47]:
s@s.T

matrix([[1, 2, 3],
        [2, 4, 6],
        [3, 6, 9]])

In [46]:
s[1]@s.T

matrix([[2, 4, 6]])

In [38]:
def fAndG(A, s):
    assert isinstance(A, np.ndarray)
    dim = A.shape
    A_rows = dim[0]
    A_cols = dim[1]
    dim = s.shape
    s_rows = dim[0]

    functionValue = ((s * (np.ones(A_rows)).dot(A))).dot(s)
    gradient = np.outer(np.ones(A_rows), (s * s))

    return functionValue, gradient

In [43]:
fAndG(np.ones((3,3)), np.array([1,2,3]))

(42.0,
 array([[1., 4., 9.],
        [1., 4., 9.],
        [1., 4., 9.]]))

In [62]:
A = np.random.uniform(0, 100, size=(10, 10))
A = normalize(A, norm='l1')

In [64]:
max(A.sum(axis=0))

1.2607409629432456

In [ ]:
np.linalg.eig(1/2 * A)